import { rspack } from "@rspack/core";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// package root (this file lives in test/infra/); entries and output are
// rooted there so `rspack build -c test/infra/rspack.config.mjs` works from
// the package root
const ROOT = path.resolve(__dirname, "../..");

/**
 * Aggressive production settings shared by all variants:
 *  - full tree shaking (usedExports/sideEffects/innerGraph)
 *  - module concatenation (scope hoisting)
 *  - SWC minifier with multiple compress passes, pure getters, no comments
 *  - es2022 output (no downlevel transpilation bloat)
 */
const swcMinifier = new rspack.SwcJsMinimizerRspackPlugin({
    minimizerOptions: {
        compress: {
            passes: 3,
            pure_getters: true,
            hoist_funs: true,
            ecma: 2020,
        },
        mangle: {
            toplevel: true,
        },
        format: {
            comments: false,
        },
    },
});

/** @returns {import('@rspack/core').Configuration} */
function makeConfig(name, entry, { externals } = {}) {
    return {
        name,
        mode: "production",
        context: ROOT,
        entry: { bundle: entry },
        target: ["web", "es2022"],
        devtool: "source-map",
        externals,
        output: {
            path: path.resolve(ROOT, "dist", name),
            filename: "[name].js",
            clean: true,
        },
        resolve: {
            extensions: [".ts", ".tsx", ".js", ".jsx"],
            extensionAlias: { ".js": [".ts", ".tsx", ".js"] },
        },
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    loader: "builtin:swc-loader",
                    options: {
                        jsc: {
                            parser: { syntax: "typescript", tsx: true },
                            transform: {
                                react: { runtime: "automatic" },
                            },
                            target: "es2022",
                        },
                    },
                },
            ],
        },
        optimization: {
            minimize: true,
            minimizer: [swcMinifier],
            concatenateModules: true,
            usedExports: true,
            providedExports: true,
            innerGraph: true,
            sideEffects: true,
            realContentHash: false,
        },
        performance: { hints: false },
        stats: "errors-warnings",
    };
}

// React is always external in measured variants: we're measuring what the
// MSAL stack adds to an app that already ships React.
const reactExternals = {
    react: "module react",
    "react-dom": "module react-dom",
    "react-dom/client": "module react-dom/client",
    "react/jsx-runtime": "module react/jsx-runtime",
};

export default [
    // Full-flow app (test/apps/app.tsx): msal-react + msal-browser + msal-common.
    makeConfig("msal-stack", "./test/apps/app.tsx", {
        externals: reactExternals,
    }),

    // Same full flow with no React layer: msal-browser + msal-common only.
    makeConfig("msal-browser-core", "./test/apps/msal-only.ts"),

    // v5 popup/silent flows additionally require a redirect-bridge page;
    // its bundle is part of what a popup-using app ships.
    makeConfig("msal-redirect-bridge", "./test/apps/redirect-bridge.ts"),

    // Tree-shaking ceiling: the entire msal-browser surface kept alive.
    makeConfig("msal-import-all", "./test/apps/msal-import-all.ts"),

    // The identical app (generated by sync-variants.mjs) on the from-scratch
    // mini-msal implementation (@mini-msal/compat + react bindings).
    makeConfig("mini-msal-stack", "./test/apps/mini-app.tsx", {
        externals: reactExternals,
    }),

    // Pay-to-play floor: @mini-msal/browser core only (createClient with
    // redirect + silent flows) — no popup feature, no React, no compat.
    makeConfig("mini-core", "./test/apps/mini-core.ts"),

    // mini's redirect-bridge page bundle (popup/silent completion is
    // bridge-based like real v5); counterpart of msal-redirect-bridge.
    makeConfig("mini-redirect-bridge", "./test/apps/mini-redirect-bridge.ts"),

    // E2E test builds pointed at the local mock IdP (test/infra/mock-idp.mjs);
    // bundle React so they run standalone. Not size-measurement targets.
    makeConfig("mini-mock-app", "./test/apps/mini-app-mock.tsx"),
    makeConfig("real-mock-app", "./test/apps/app-mock.tsx"),

    // Conformance-suite harness pages (test/conformance/run.mjs drives these):
    // bare pages exposing the library namespace + a client factory as globals.
    makeConfig("conformance-real", "./test/apps/harness/harness-real.ts"),
    makeConfig("conformance-mini", "./test/apps/harness/harness-mini.ts"),

    // Real Entra ID test builds (authConfig.ts clientId), served at the site
    // root via dist/index.html. React bundled; not measurement targets.
    makeConfig("real-aad-app", "./test/apps/app.tsx"),
    makeConfig("mini-aad-app", "./test/apps/mini-app.tsx"),
];
