import { rspack } from "@rspack/core";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// package root (this file lives in test/infra/); entries and output are
// rooted there so `rspack build -c test/infra/rspack.config.mjs` works from
// the package root
const ROOT = path.resolve(__dirname, "../..");

/**
 * Aggressive production settings shared by all variants:
 *  - full tree shaking (usedExports/sideEffects/innerGraph)
 *  - module concatenation (scope hoisting)
 *  - SWC minifier with multiple compress passes, pure getters, no comments
 *  - es2022 output (no downlevel transpilation bloat)
 */
const swcMinifier = new rspack.SwcJsMinimizerRspackPlugin({
    minimizerOptions: {
        compress: {
            passes: 3,
            pure_getters: true,
            hoist_funs: true,
            ecma: 2020,
        },
        mangle: {
            toplevel: true,
        },
        format: {
            comments: false,
        },
    },
});

/** @returns {import('@rspack/core').Configuration} */
function makeConfig(name, entry, { externals } = {}) {
    return {
        name,
        mode: "production",
        context: ROOT,
        entry: { bundle: entry },
        target: ["web", "es2022"],
        devtool: "source-map",
        externals,
        output: {
            path: path.resolve(ROOT, "dist", name),
            filename: "[name].js",
            clean: true,
        },
        resolve: {
            extensions: [".ts", ".tsx", ".js", ".jsx"],
            extensionAlias: { ".js": [".ts", ".tsx", ".js"] },
            // internal builds consume @mini-msal/* straight from src/*.ts;
            // consumers resolve the packages' built dist (see pack:check)
            conditionNames: ["mini-msal-src", "..."],
        },
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    loader: "builtin:swc-loader",
                    options: {
                        jsc: {
                            parser: { syntax: "typescript", tsx: true },
                            transform: {
                                react: { runtime: "automatic" },
                            },
                            target: "es2022",
                        },
                    },
                },
            ],
        },
        optimization: {
            minimize: true,
            minimizer: [swcMinifier],
            concatenateModules: true,
            usedExports: true,
            providedExports: true,
            innerGraph: true,
            sideEffects: true,
            realContentHash: false,
        },
        performance: { hints: false },
        stats: "errors-warnings",
    };
}

// D3 example smoke builds: same example sources pointed at the local mock
// IdP by swapping each example's ./authConfig.js module (React bundled so
// they run standalone). Driven by test/examples/smoke.mjs; not size targets
// (measure.mjs excludes "*smoke*").
const MOCK_AUTH_CONFIG = path.resolve(ROOT, "test/apps/authConfig.mock.ts");
function makeSmokeConfig(name, entry) {
    const config = makeConfig(name, entry);
    config.plugins = [
        new rspack.NormalModuleReplacementPlugin(
            /[\\/]authConfig(\.js)?$/,
            MOCK_AUTH_CONFIG
        ),
    ];
    return config;
}

// React is always external in measured variants: we're measuring what the
// MSAL stack adds to an app that already ships React.
const reactExternals = {
    react: "module react",
    "react-dom": "module react-dom",
    "react-dom/client": "module react-dom/client",
    "react/jsx-runtime": "module react/jsx-runtime",
};

export default [
    // Full-flow app (test/apps/app.tsx): msal-react + msal-browser + msal-common.
    makeConfig("msal-stack", "./test/apps/app.tsx", {
        externals: reactExternals,
    }),

    // Same full flow with no React layer: msal-browser + msal-common only.
    makeConfig("msal-browser-core", "./test/apps/msal-only.ts"),

    // v5 popup/silent flows additionally require a redirect-bridge page;
    // its bundle is part of what a popup-using app ships.
    makeConfig("msal-redirect-bridge", "./test/apps/redirect-bridge.ts"),

    // Tree-shaking ceiling: the entire msal-browser surface kept alive.
    makeConfig("msal-import-all", "./test/apps/msal-import-all.ts"),

    // The identical app (generated by sync-variants.mjs) on the from-scratch
    // mini-msal implementation (@mini-msal/compat + react bindings).
    makeConfig("mini-msal-stack", "./test/apps/mini-app.tsx", {
        externals: reactExternals,
    }),

    // Full @mini-msal/compat drop-in with no React layer (generated from
    // msal-only.ts); counterpart of msal-browser-core.
    makeConfig("mini-compat", "./test/apps/mini-only.ts"),

    // Pay-to-play floor: @mini-msal/browser core only (createClient with
    // redirect + silent flows) — no popup feature, no React, no compat.
    makeConfig("mini-core", "./test/apps/mini-core.ts"),

    // mini's redirect-bridge page bundle (popup/silent completion is
    // bridge-based like real v5); counterpart of msal-redirect-bridge.
    makeConfig("mini-redirect-bridge", "./test/apps/mini-redirect-bridge.ts"),

    // E2E test builds pointed at the local mock IdP (test/infra/mock-idp.mjs);
    // bundle React so they run standalone. Not size-measurement targets.
    makeConfig("mini-mock-app", "./test/apps/mini-app-mock.tsx"),
    makeConfig("real-mock-app", "./test/apps/app-mock.tsx"),

    // Conformance-suite harness pages (test/conformance/run.mjs drives these):
    // bare pages exposing the library namespace + a client factory as globals.
    makeConfig("conformance-real", "./test/apps/harness/harness-real.ts"),
    makeConfig("conformance-mini", "./test/apps/harness/harness-mini.ts"),

    // Seam-hardening harness (test/unit/seams.mjs): core + feature closures
    // as globals so checks compose arbitrary subsets. Not a size target.
    makeConfig(
        "conformance-mini-core",
        "./test/apps/harness/harness-mini-core.ts"
    ),

    // React-bindings conformance harnesses (area 12-react): same globals as
    // above plus __mount/fixtures; React is bundled (not a size target).
    makeConfig(
        "conformance-react-real",
        "./test/apps/harness/harness-react-real.tsx"
    ),
    makeConfig(
        "conformance-react-mini",
        "./test/apps/harness/harness-react-mini.tsx"
    ),

    // Real Entra ID test builds (authConfig.ts clientId), served at the site
    // root via dist/index.html. React bundled; not measurement targets.
    makeConfig("real-aad-app", "./test/apps/app.tsx"),
    makeConfig("mini-aad-app", "./test/apps/mini-app.tsx"),

    // Consumer examples (examples/*), one per consumption profile, measured
    // with the size-matrix settings (React external where present) so each
    // doubles as a size regression check in `npm run measure`.
    makeConfig("example-core-redirect", "./examples/core-redirect/main.ts"),
    makeConfig("example-core-popup", "./examples/core-popup/main.ts"),
    makeConfig("example-compat", "./examples/compat/main.ts"),
    makeConfig("example-react", "./examples/react/main.tsx", {
        externals: reactExternals,
    }),

    // The same examples runnable against the mock IdP (smoke check:
    // `npm run examples:smoke`).
    makeSmokeConfig(
        "example-core-redirect-smoke",
        "./examples/core-redirect/main.ts"
    ),
    makeSmokeConfig("example-core-popup-smoke", "./examples/core-popup/main.ts"),
    makeSmokeConfig("example-compat-smoke", "./examples/compat/main.ts"),
    makeSmokeConfig("example-react-smoke", "./examples/react/main.tsx"),
];
